
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NEWLINE RECETTE SECTION TEXTrecette : RECETTE section_ingredients section_etapessection_ingredients : SECTION ingredientsingredients : TEXT ingredients\n                   | TEXTsection_etapes : SECTION etapesetapes : TEXT etapes\n              | TEXT'
    
_lr_action_items = {'RECETTE':([0,],[2,]),'$end':([1,5,9,10,12,],[0,-1,-5,-7,-6,]),'SECTION':([2,3,7,8,11,],[4,6,-2,-4,-3,]),'TEXT':([4,6,8,10,],[8,10,8,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'recette':([0,],[1,]),'section_ingredients':([2,],[3,]),'section_etapes':([3,],[5,]),'ingredients':([4,8,],[7,11,]),'etapes':([6,10,],[9,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> recette","S'",1,None,None,None),
  ('recette -> RECETTE section_ingredients section_etapes','recette',3,'p_recette','recipe_parser.py',5),
  ('section_ingredients -> SECTION ingredients','section_ingredients',2,'p_section_ingredients','recipe_parser.py',13),
  ('ingredients -> TEXT ingredients','ingredients',2,'p_ingredients','recipe_parser.py',19),
  ('ingredients -> TEXT','ingredients',1,'p_ingredients','recipe_parser.py',20),
  ('section_etapes -> SECTION etapes','section_etapes',2,'p_section_etapes','recipe_parser.py',24),
  ('etapes -> TEXT etapes','etapes',2,'p_etapes','recipe_parser.py',30),
  ('etapes -> TEXT','etapes',1,'p_etapes','recipe_parser.py',31),
]
